shortcuts:
  # alias
  style:
    pipeline_name: format

  dev:
    pipeline_name: qa
    args:
      clean: False
      integration: False
      stats: False

  ci:
    pipeline_name: qa
    args:
      format: False
      integration: False

  ci_docker:
    pipeline_name: qa
    args:
      npm: False
      format: False
      integration: False
      stats: False
